/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pbo2uts;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
public class FormKRS extends javax.swing.JInternalFrame {
DefaultTableModel model;
    /**
     * Creates new form FormKRS
     */
    public FormKRS() {
        initComponents();
        txtSks.setForeground(Color.WHITE);
        txtSks.setBackground(new Color(30,30,30));
       isiComboNim();
    isiComboMk();
    
    // Matikan edit manual agar angka hanya dari sistem
    txtMataKuliah.setEditable(false);
    txtSks.setEditable(false);
    
    // Bersihkan baris default tabel jika ada
    ((DefaultTableModel)tblKrs.getModel()).setRowCount(0);
    }
    
private void hitungTotal() {
    int baris = tblKrs.getRowCount();
    int totalSks = 0;
    
    for (int i = 0; i < baris; i++) {
        try {
            // Ambil kolom ke-6 (index 5) yaitu SKS
            String s = tblKrs.getValueAt(i, 5).toString();
            totalSks += Integer.parseInt(s);
        } catch (Exception e) {
            totalSks += 0;
        }
    }
    txtMataKuliah.setText(String.valueOf(baris));
    txtSks.setText(String.valueOf(totalSks));
    
    if (Integer.parseInt(txtSks.getText()) >= 24) {
    txtSks.setForeground(java.awt.Color.RED);
} else {
    txtSks.setForeground(java.awt.Color.WHITE);
}
}
    private void isiComboNim() {
    try {
        Connection conn = koneksi.getKoneksi();
        ResultSet rs = conn.createStatement().executeQuery("SELECT nim FROM mahasiswa");
        while(rs.next()) cbNim.addItem(rs.getString("nim"));
    } catch (Exception e) {}
}

private void isiComboMk() {
    try {
        Connection conn = koneksi.getKoneksi();
        ResultSet rs = conn.createStatement().executeQuery("SELECT kode_mk FROM matakuliah");
        while(rs.next()) cbMk.addItem(rs.getString("kode_mk"));
    } catch (Exception e) {}
}
  
   
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKrs = new javax.swing.JTable();
        cbNim = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        lblTotalSks = new javax.swing.JLabel();
        lblJumlahMk = new javax.swing.JLabel();
        txtMataKuliah = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        cbMk = new javax.swing.JComboBox<>();
        txtNamaMk = new javax.swing.JTextField();
        txtSemesterMk = new javax.swing.JTextField();
        txtSksMk = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtSks = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKrs1 = new javax.swing.JTable();
        cbNim1 = new javax.swing.JComboBox<>();
        btnTambah1 = new javax.swing.JButton();
        btnHapus1 = new javax.swing.JButton();
        lblTotalSks1 = new javax.swing.JLabel();
        lblJumlahMk1 = new javax.swing.JLabel();
        txtMataKuliah1 = new javax.swing.JTextField();
        btnSubmit1 = new javax.swing.JButton();
        cbMk1 = new javax.swing.JComboBox<>();
        txtNamaMk1 = new javax.swing.JTextField();
        txtSemesterMk1 = new javax.swing.JTextField();
        txtSksMk1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtSks1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tblKrs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nim", "Kode", "Mata Kuliah", "Semester", "Sks"
            }
        ));
        jScrollPane1.setViewportView(tblKrs);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 631;
        gridBagConstraints.ipady = 429;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(26, 46, 0, 51);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        cbNim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIM" }));
        cbNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNimActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 46, 0, 0);
        getContentPane().add(cbNim, gridBagConstraints);

        btnTambah.setText("Tambah");
        btnTambah.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnTambahItemStateChanged(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 46, 0, 0);
        getContentPane().add(btnTambah, gridBagConstraints);

        btnHapus.setText("Hapus");
        btnHapus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnHapusItemStateChanged(evt);
            }
        });
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 11, 0, 0);
        getContentPane().add(btnHapus, gridBagConstraints);

        lblTotalSks.setText("Jumlah SKS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 46, 0, 0);
        getContentPane().add(lblTotalSks, gridBagConstraints);

        lblJumlahMk.setText("Jumlah Mata Kuliah");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 46, 0, 0);
        getContentPane().add(lblJumlahMk, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 32, 0, 0);
        getContentPane().add(txtMataKuliah, gridBagConstraints);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 36, 19, 0);
        getContentPane().add(btnSubmit, gridBagConstraints);

        cbMk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode Mk" }));
        cbMk.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMkItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 1, 0, 0);
        getContentPane().add(cbMk, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 69;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 14, 0, 0);
        getContentPane().add(txtNamaMk, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 38, 0, 0);
        getContentPane().add(txtSemesterMk, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 45, 0, 0);
        getContentPane().add(txtSksMk, gridBagConstraints);

        jButton1.setText("Tutup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 38, 0, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        txtSks.setForeground(new java.awt.Color(255, 255, 255));
        txtSks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSksActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 32, 0, 0);
        getContentPane().add(txtSks, gridBagConstraints);

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);

        tblKrs1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nim", "Kode", "Mata Kuliah", "Semester", "Sks"
            }
        ));
        jScrollPane2.setViewportView(tblKrs1);

        cbNim1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIM" }));
        cbNim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNim1ActionPerformed(evt);
            }
        });

        btnTambah1.setText("Tambah");
        btnTambah1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnTambah1ItemStateChanged(evt);
            }
        });
        btnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah1ActionPerformed(evt);
            }
        });

        btnHapus1.setText("Hapus");
        btnHapus1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnHapus1ItemStateChanged(evt);
            }
        });
        btnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus1ActionPerformed(evt);
            }
        });

        lblTotalSks1.setText("Jumlah SKS");

        lblJumlahMk1.setText("Jumlah Mata Kuliah");

        btnSubmit1.setText("Submit");
        btnSubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit1ActionPerformed(evt);
            }
        });

        cbMk1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode Mk" }));
        cbMk1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMk1ItemStateChanged(evt);
            }
        });

        jButton2.setText("Tutup");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubmit1)
                    .addComponent(jScrollPane2)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(cbNim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbMk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNamaMk1)
                            .addComponent(btnTambah1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(btnHapus1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(txtSemesterMk1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSksMk1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJumlahMk1)
                            .addComponent(lblTotalSks1))
                        .addGap(26, 26, 26)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMataKuliah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSks1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaMk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSemesterMk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSksMk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah1)
                    .addComponent(btnHapus1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlahMk1)
                    .addComponent(txtMataKuliah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalSks1)
                    .addComponent(txtSks1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnSubmit1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -624;
        gridBagConstraints.ipady = -552;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jInternalFrame1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNimActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
try {
       
        int sksBaru = Integer.parseInt(txtSksMk.getText()); 
        
       
        int sksSekarang = 0;
        if (!txtSks.getText().isEmpty()) {
            sksSekarang = Integer.parseInt(txtSks.getText());
        }

        // 3. CEK LIMIT: Apakah jika ditambah akan melebihi 24?
        if (sksSekarang + sksBaru > 24) {
            JOptionPane.showMessageDialog(this, 
                "Batas maksimal 24 SKS! \nSKS saat ini: " + sksSekarang + "\nSKS yang akan ditambah: " + sksBaru, 
                "Peringatan Limit SKS", 
                JOptionPane.WARNING_MESSAGE);
            return; // Berhenti, data tidak akan masuk ke tabel
        }

        // 4. Jika lolos validasi, baru masukkan ke tabel
        DefaultTableModel model = (DefaultTableModel) tblKrs.getModel();
        int no = tblKrs.getRowCount() + 1;
        
        String nim = cbNim.getSelectedItem().toString();
        String kode = cbMk.getSelectedItem().toString();
        String matkul = txtNamaMk.getText();
        String sem = txtSemesterMk.getText();
        String sks = txtSksMk.getText();
        
        // Cek apakah Kode MK sudah ada di tabel
for (int i = 0; i < tblKrs.getRowCount(); i++) {
    String kodeDiTabel = tblKrs.getValueAt(i, 2).toString(); // kolom kode
    if (kodeDiTabel.equals(cbMk.getSelectedItem().toString())) {
        JOptionPane.showMessageDialog(this, "Mata kuliah ini sudah kamu ambil!");
        return;
    }
}
        model.addRow(new Object[]{no, nim, kode, matkul, sem, sks});
        
      
        hitungTotal();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Pilih mata kuliah terlebih dahulu!");
    }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
// 1. Ambil index baris yang dipilih user di tabel
    int barisTerpilih = tblKrs.getSelectedRow();
    
    // 2. Cek apakah ada baris yang dipilih
    if (barisTerpilih != -1) {
        DefaultTableModel model = (DefaultTableModel) tblKrs.getModel();
        
        // 3. Hapus baris tersebut dari model tabel
        model.removeRow(barisTerpilih);
        
        // 4. Update Nomor Urut (Agar nomor kembali berurutan 1, 2, 3...)
        for (int i = 0; i < model.getRowCount(); i++) {
            model.setValueAt(i + 1, i, 0); // Set kolom index 0 dengan nomor baru
        }
        
        // 5. Panggil fungsi hitungTotal agar Jumlah SKS berkurang otomatis
        hitungTotal();
        
    } else {
        // Jika user klik hapus tapi belum pilih baris di tabel
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih baris di tabel yang ingin dihapus!");
    }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
int baris = tblKrs.getRowCount();
    if (baris == 0) {
        JOptionPane.showMessageDialog(this, "Tabel kosong, tidak ada yang disubmit!");
        return;
    }

    try {
        Connection conn = koneksi.getKoneksi();
        String sql = "INSERT INTO krs (nim, kode_mk, kode_dosen, thn_akademik) VALUES (?, ?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql);
        
        for (int i = 0; i < baris; i++) {
            pst.setString(1, tblKrs.getValueAt(i, 1).toString()); // Nim
            pst.setString(2, tblKrs.getValueAt(i, 2).toString()); // Kode MK
            pst.setString(3, "D001"); // Kode Dosen default atau buat combo dosen jika perlu
            pst.setString(4, "2026/2027 Genap"); // Tahun Akademik
            pst.addBatch();
        }
        
        pst.executeBatch();
        JOptionPane.showMessageDialog(this, "Berhasil simpan ke Database!");
        
        // Reset Tabel
        DefaultTableModel model = (DefaultTableModel) tblKrs.getModel();
        model.setRowCount(0);
        txtMataKuliah.setText("");
        txtSks.setText("");
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal Submit: " + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnTambahItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnTambahItemStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahItemStateChanged

    private void cbMkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMkItemStateChanged
if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        try {
            java.sql.Connection conn = koneksi.getKoneksi();
            java.sql.PreparedStatement pst = conn.prepareStatement("SELECT * FROM matakuliah WHERE kode_mk = ?");
            pst.setString(1, cbMk.getSelectedItem().toString());
            java.sql.ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                // Sekarang pakai .setText() karena sudah jadi TextField
                txtNamaMk.setText(rs.getString("nama_mk"));
                txtSemesterMk.setText(rs.getString("semester"));
                txtSksMk.setText(rs.getString("sks"));
            }
        } catch (Exception e) {
            System.err.println("Gagal sinkron: " + e.getMessage());
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMkItemStateChanged

    private void btnHapusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnHapusItemStateChanged
int baris = tblKrs.getSelectedRow();
    if (baris != -1) {
        DefaultTableModel model = (DefaultTableModel) tblKrs.getModel();
        model.removeRow(baris);
        
        // Susun ulang nomor urut setelah dihapus
        for (int i = 0; i < model.getRowCount(); i++) {
            model.setValueAt(i + 1, i, 0);
        }
        hitungTotal();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menutup form ini?", 
            "Konfirmasi Tutup", 
            JOptionPane.YES_NO_OPTION);
            
    if (konfirmasi == JOptionPane.YES_OPTION) {
        this.dispose();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbNim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNim1ActionPerformed

    private void btnTambah1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnTambah1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambah1ItemStateChanged

    private void btnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambah1ActionPerformed

    private void btnHapus1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnHapus1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapus1ItemStateChanged

    private void btnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapus1ActionPerformed

    private void btnSubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmit1ActionPerformed

    private void cbMk1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMk1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMk1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtSksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSksActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHapus1;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmit1;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTambah1;
    private javax.swing.JComboBox<String> cbMk;
    private javax.swing.JComboBox<String> cbMk1;
    private javax.swing.JComboBox<String> cbNim;
    private javax.swing.JComboBox<String> cbNim1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblJumlahMk;
    private javax.swing.JLabel lblJumlahMk1;
    private javax.swing.JLabel lblTotalSks;
    private javax.swing.JLabel lblTotalSks1;
    private javax.swing.JTable tblKrs;
    private javax.swing.JTable tblKrs1;
    private javax.swing.JTextField txtMataKuliah;
    private javax.swing.JTextField txtMataKuliah1;
    private javax.swing.JTextField txtNamaMk;
    private javax.swing.JTextField txtNamaMk1;
    private javax.swing.JTextField txtSemesterMk;
    private javax.swing.JTextField txtSemesterMk1;
    private javax.swing.JTextField txtSks;
    private javax.swing.JTextField txtSks1;
    private javax.swing.JTextField txtSksMk;
    private javax.swing.JTextField txtSksMk1;
    // End of variables declaration//GEN-END:variables
}
