/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pbo2uts;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author irsya
 */
public class FormMatakuliah extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormMatakuliah
     */
    public FormMatakuliah() {
        initComponents();
        loadData();
        resetForm();
        loadDosenToCombo();
    }
    private void loadData() {
    DefaultTableModel model = (DefaultTableModel) tblMk.getModel();
    model.setRowCount(0);
    try {
        java.sql.Connection conn = koneksi.getKoneksi();
        java.sql.ResultSet rs = conn.createStatement().executeQuery("SELECT * FROM matakuliah");
        while(rs.next()){
            model.addRow(new Object[]{
                rs.getString("kode_mk"),
                rs.getString("nama_mk"),
                rs.getInt("sks"),
                rs.getInt("semester")
            });
        }
    } catch (Exception e) {
        System.out.println(e.getMessage());
    }
}
    private void resetForm() {
    txtKode.setText("");
    txtNama.setText("");
    txtSks.setText("");
    txtSemester.setText("");
    txtKode.setEditable(true); // Buka kunci kode MK
    cbDosen.setSelectedIndex(0);
    txtKode.requestFocus();
}
    private void loadDosenToCombo() {
    try {
        java.sql.Connection conn = koneksi.getKoneksi();
        String sql = "SELECT nama_dosen FROM dosen"; // Ambil kolom nama dari tabel dosen
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();
        
        cbDosen.removeAllItems();
        cbDosen.addItem("- Pilih Dosen -");
        
        while (rs.next()) {
            cbDosen.addItem(rs.getString("nama_dosen"));
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal muat dosen: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtSks = new javax.swing.JTextField();
        txtSemester = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMk = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        cbDosen = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Kode Matkul");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 134, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Nama Matkul");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 134, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("SKS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 134, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("Semester");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 134, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 43, 0, 0);
        getContentPane().add(txtKode, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 43, 0, 0);
        getContentPane().add(txtNama, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 43, 0, 0);
        getContentPane().add(txtSks, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 43, 0, 0);
        getContentPane().add(txtSemester, gridBagConstraints);

        tblMk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode", "Mata Kuliah", "SKS", "Semester"
            }
        ));
        tblMk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMk);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 489;
        gridBagConstraints.ipady = 373;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 134, 15, 109);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 110, 0, 109);
        getContentPane().add(btnTambah, gridBagConstraints);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 111, 0, 109);
        getContentPane().add(btnHapus, gridBagConstraints);

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 111, 0, 109);
        getContentPane().add(btnUbah, gridBagConstraints);

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 134, 0, 0);
        getContentPane().add(btnCari, gridBagConstraints);

        btnTutup.setText("Tutup");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 111, 0, 109);
        getContentPane().add(btnTutup, gridBagConstraints);

        cbDosen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 12, 0, 0);
        getContentPane().add(cbDosen, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
try {
    java.sql.Connection conn = koneksi.getKoneksi();
    String sql = "INSERT INTO matakuliah (kode_mk, nama_mk, sks, semester, nama_dosen) VALUES (?, ?, ?, ?, ?)";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    
    pst.setString(1, txtKode.getText());
    pst.setString(2, txtNama.getText());
    pst.setInt(3, Integer.parseInt(txtSks.getText()));
    pst.setInt(4, Integer.parseInt(txtSemester.getText()));
    
    // Pastikan JComboBox dosen sudah terpilih
    String dosen = cbDosen.getSelectedItem().toString();
    if (dosen.equals("- Pilih Dosen -")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih dosennya dulu!");
        return;
    }
    pst.setString(5, dosen);
    
    pst.execute();
    javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Ditambah!");
    loadData(); 
    resetForm(); 
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
if (txtKode.getText().equals("") || txtNama.getText().equals("") || 
    txtSks.getText().equals("") || txtSemester.getText().equals("") || 
    cbDosen.getSelectedIndex() == 0) {
    
    JOptionPane.showMessageDialog(this, "Pilih data di tabel dan pastikan semua kolom terisi, termasuk Dosen!");
    return;
}

try {
    java.sql.Connection conn = koneksi.getKoneksi();
    
    // PERBAIKAN: Tambahkan nama_dosen=? sebelum WHERE
    String sql = "UPDATE matakuliah SET nama_mk=?, sks=?, semester=?, nama_dosen=? WHERE kode_mk=?";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    
    // Sesuaikan urutan parameter dengan tanda tanya (?) di atas
    pst.setString(1, txtNama.getText());
    pst.setInt(2, Integer.parseInt(txtSks.getText()));
    pst.setInt(3, Integer.parseInt(txtSemester.getText()));
    pst.setString(4, cbDosen.getSelectedItem().toString()); // Parameter dosen (baru ditambahkan)
    pst.setString(5, txtKode.getText()); // WHERE kode_mk (geser ke nomor 5)
    
    pst.execute();
    JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui!");
    
    loadData();  // Refresh tabel
    resetForm(); // Reset semua field termasuk ComboBox
    
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "SKS dan Semester harus berupa angka!");
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Gagal Ubah: " + e.getMessage());
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
String cari = JOptionPane.showInputDialog(this, "Cari Nama atau Kode MK:");
    if (cari != null) {
        DefaultTableModel model = (DefaultTableModel) tblMk.getModel();
        model.setRowCount(0);
        try {
            java.sql.Connection conn = koneksi.getKoneksi();
            String sql = "SELECT * FROM matakuliah WHERE nama_mk LIKE ? OR kode_mk LIKE ?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + cari + "%");
            pst.setString(2, "%" + cari + "%");
            java.sql.ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("kode_mk"),
                    rs.getString("nama_mk"),
                    rs.getInt("sks"),
                    rs.getInt("semester")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menutup form ini?", 
            "Konfirmasi Tutup", 
            JOptionPane.YES_NO_OPTION);
            
    if (konfirmasi == JOptionPane.YES_OPTION) {
        this.dispose();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTutupActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
int opt = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin hapus data ini?", "Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
    if (opt == 0) {
        try {
            java.sql.Connection conn = koneksi.getKoneksi();
            String sql = "DELETE FROM matakuliah WHERE kode_mk=?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtKode.getText());
            pst.execute();
            
            loadData();
            resetForm();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblMkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMkMouseClicked
int baris = tblMk.getSelectedRow();
    txtKode.setText(tblMk.getValueAt(baris, 0).toString());
    txtNama.setText(tblMk.getValueAt(baris, 1).toString());
    txtSks.setText(tblMk.getValueAt(baris, 2).toString());
    txtSemester.setText(tblMk.getValueAt(baris, 3).toString());
    
    
    txtKode.setEditable(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMkMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnTutup;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbDosen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMk;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtSemester;
    private javax.swing.JTextField txtSks;
    // End of variables declaration//GEN-END:variables


}
