/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pbo2uts;

import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author irsya
 */
public class FormNilai extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormNilai
     */
    public FormNilai() {
        initComponents();
        // 1. Kosongkan tabel saat form pertama kali dibuka
    DefaultTableModel model = (DefaultTableModel) tblNilai.getModel();
    model.setRowCount(0);
    //txtNim.requestFocus();
    isiComboNim();
    }
    private void isiComboNim() {
    try {
        java.sql.Connection conn = koneksi.getKoneksi();
        // Ambil NIM dari tabel mahasiswa atau KRS
        String sql = "SELECT DISTINCT nim FROM krs"; 
        java.sql.ResultSet rs = conn.createStatement().executeQuery(sql);
        cbNim.removeAllItems();
        cbNim.addItem("- Pilih NIM -");
        while (rs.next()) {
            cbNim.addItem(rs.getString("nim"));
        }
    } catch (Exception e) {
        System.err.println("Gagal isi combo NIM: " + e.getMessage());
    }
}
    private String hitungGrade(double nilai) {
    if (nilai >= 85) return "A";
    else if (nilai >= 80) return "AB";
    else if (nilai >= 70) return "B";
    else if (nilai >= 60) return "BC";
    else if (nilai >= 50) return "C";
    else if (nilai >= 40) return "D";
    else return "E";
}
    private double getBobot(String grade) {
    switch (grade) {
        case "A":  return 4.0;
        case "AB": return 3.5;
        case "B":  return 3.0;
        case "BC": return 2.5;
        case "C":  return 2.0;
        case "D":  return 1.0;
        default:   return 0.0;
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUts = new javax.swing.JTextField();
        txtUas = new javax.swing.JTextField();
        txtTugas = new javax.swing.JTextField();
        txtAbsensi = new javax.swing.JTextField();
        btnInput = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNilai = new javax.swing.JTable();
        btnTutup = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbMatkul = new javax.swing.JComboBox<>();
        cbNim = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("NIM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 179, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("UTS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 179, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("UAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 179, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("TUGAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 179, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setText("Absensi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 179, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 24, 0, 0);
        getContentPane().add(txtUts, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 24, 0, 0);
        getContentPane().add(txtUas, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 24, 0, 0);
        getContentPane().add(txtTugas, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 24, 0, 0);
        getContentPane().add(txtAbsensi, gridBagConstraints);

        btnInput.setText("Input");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 179, 0, 0);
        getContentPane().add(btnInput, gridBagConstraints);

        tblNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Mata Kuliah", "UTS", "UAS", "TUGAS", "Absensi", "Nilai", "Grade"
            }
        ));
        jScrollPane1.setViewportView(tblNilai);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 436;
        gridBagConstraints.ipady = 313;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 179, 0, 52);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        btnTutup.setText("Tutup");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 18, 0, 0);
        getContentPane().add(btnTutup, gridBagConstraints);

        jLabel6.setText("Mata Kuliah");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 26, 0, 0);
        getContentPane().add(jLabel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 30, 0, 0);
        getContentPane().add(cbMatkul, gridBagConstraints);

        cbNim.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNimItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 24, 0, 0);
        getContentPane().add(cbNim, gridBagConstraints);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 179, 6, 0);
        getContentPane().add(btnSubmit, gridBagConstraints);

        jButton1.setText("Hapus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 29, 0, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
try {
    // 1. Ambil data dari inputan
    String nim = cbNim.getSelectedItem().toString();
    
    // Validasi jika NIM masih "- Pilih NIM -"
    if (cbNim.getSelectedIndex() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih NIM dulu");
        return;
    }

    // Mengambil teks dari ComboBox Matkul (format: KODE - NAMA)
    String matkulFull = cbMatkul.getSelectedItem().toString();
    String namaMk = matkulFull.split(" - ")[1]; 

    // --- JURUS ANTI DUPLIKAT ---
    for (int i = 0; i < tblNilai.getRowCount(); i++) {
        String nimDiTabel = tblNilai.getValueAt(i, 0).toString();
        String matkulDiTabel = tblNilai.getValueAt(i, 1).toString();

        // Jika NIM dan Matkul sudah ada di baris tabel, blokir!
        if (nim.equals(nimDiTabel) && namaMk.equals(matkulDiTabel)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Matakuliah " + namaMk + " sudah diinput untuk NIM ini!", 
                "Duplikat", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Berhenti di sini, kodingan bawah tidak akan jalan
        }
    }

    // Ambil nilai dari TextField
    double uts = Double.parseDouble(txtUts.getText());
    double uas = Double.parseDouble(txtUas.getText());
    double tugas = Double.parseDouble(txtTugas.getText());
    double absen = Double.parseDouble(txtAbsensi.getText());

    // 2. Hitung Nilai Akhir & Grade
    double nilaiAkhir = (absen * 0.1) + (tugas * 0.2) + (uts * 0.3) + (uas * 0.4);
    String grade = hitungGrade(nilaiAkhir);

    // 3. Masukkan ke Tabel
    DefaultTableModel model = (DefaultTableModel) tblNilai.getModel();
    model.addRow(new Object[]{
        nim, 
        namaMk, 
        uts, 
        uas, 
        tugas, 
        absen, 
        nilaiAkhir, 
        grade
    });
    
    // 4. JURUS RESET (NIM TETEP NEMPEL)
    // cbNim.setSelectedIndex(0); // <--- BARIS INI DIMATIKAN BIAR NIM GAK CLEAR
    
    cbMatkul.setSelectedIndex(0); // Cuma Matkul yang balik ke awal
    txtUts.setText("");
    txtUas.setText("");
    txtTugas.setText("");
    txtAbsensi.setText("");
    
    // Balikin kursor ke Matkul biar cepet buat input MK selanjutnya
    cbMatkul.requestFocus();
    
    javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");

} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: Nilai harus berupa angka!");
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInputActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menutup form ini?", 
            "Konfirmasi Tutup", 
            JOptionPane.YES_NO_OPTION);
            
    if (konfirmasi == JOptionPane.YES_OPTION) {
        this.dispose();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTutupActionPerformed

    private void cbNimItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNimItemStateChanged
if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        String nim = cbNim.getSelectedItem().toString();
        if (!nim.equals("- Pilih NIM -")) {
            try {
                java.sql.Connection conn = koneksi.getKoneksi();
                // Query JOIN untuk ambil Nama Matkul berdasarkan NIM di tabel KRS
                String sql = "SELECT krs.kode_mk, matakuliah.nama_mk FROM krs "
                           + "JOIN matakuliah ON krs.kode_mk = matakuliah.kode_mk "
                           + "WHERE krs.nim = '" + nim + "'";
                java.sql.ResultSet rs = conn.createStatement().executeQuery(sql);
                
                cbMatkul.removeAllItems();
                while (rs.next()) {
                    // Kita simpan format "KODE - NAMA" agar mudah dipisah nanti
                    cbMatkul.addItem(rs.getString("kode_mk") + " - " + rs.getString("nama_mk"));
                }
            } catch (Exception e) {
                System.err.println("Gagal isi combo Matkul: " + e.getMessage());
            }
        }
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNimItemStateChanged

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
try {
        java.sql.Connection conn = koneksi.getKoneksi();
        DefaultTableModel model = (DefaultTableModel) tblNilai.getModel();
        
        // Cek apakah tabel kosong
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Tabel masih kosong! Input dulu nilainya.");
            return;
        }

        // Loop untuk menyimpan SEMUA baris yang ada di tabel ke Database
        String sql = "INSERT INTO nilai (nim, nama_mk, uts, uas, tugas, absen, nilai_akhir, grade) VALUES (?,?,?,?,?,?,?,?)";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);

        for (int i = 0; i < model.getRowCount(); i++) {
            pst.setString(1, model.getValueAt(i, 0).toString()); // nim
            pst.setString(2, model.getValueAt(i, 1).toString()); // nama_mk
            pst.setDouble(3, Double.parseDouble(model.getValueAt(i, 2).toString())); // uts
            pst.setDouble(4, Double.parseDouble(model.getValueAt(i, 3).toString())); // uas
            pst.setDouble(5, Double.parseDouble(model.getValueAt(i, 4).toString())); // tugas
            pst.setDouble(6, Double.parseDouble(model.getValueAt(i, 5).toString())); // absen
            pst.setDouble(7, Double.parseDouble(model.getValueAt(i, 6).toString())); // nilai_akhir
            pst.setString(8, model.getValueAt(i, 7).toString()); // grade
            pst.addBatch(); // Tambahkan ke antrean batch
        }

        pst.executeBatch(); // Eksekusi semua data sekaligus
        JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan ke Database!");
        
        // Bersihkan tabel setelah berhasil submit
        model.setRowCount(0);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal simpan: " + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
DefaultTableModel model = (DefaultTableModel) tblNilai.getModel();
    int barisTerpilih = tblNilai.getSelectedRow();

    if (barisTerpilih != -1) {
        // Konfirmasi sebelum hapus (opsional tapi bagus)
        int konfirmasi = JOptionPane.showConfirmDialog(this, 
                "Hapus baris terpilih dari daftar?", "Konfirmasi", 
                JOptionPane.YES_NO_OPTION);
        
        if (konfirmasi == JOptionPane.YES_OPTION) {
            model.removeRow(barisTerpilih);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih dulu baris yang mau dihapus di tabel");
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnTutup;
    private javax.swing.JComboBox<String> cbMatkul;
    private javax.swing.JComboBox<String> cbNim;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNilai;
    private javax.swing.JTextField txtAbsensi;
    private javax.swing.JTextField txtTugas;
    private javax.swing.JTextField txtUas;
    private javax.swing.JTextField txtUts;
    // End of variables declaration//GEN-END:variables
}
