/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pbo2uts;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.io.FileOutputStream;

/**
 *
 * @author irsya
 */
public class FormDataNilai extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormDataNilai
     */
    public FormDataNilai() {
        initComponents();
         loadData();
    }
    private void loadData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("NIM"); // Tambahkan kolom NIM agar tahu ini nilai siapa
    model.addColumn("Mata Kuliah");
    model.addColumn("Score");
    model.addColumn("Grade");

    try {
        int no = 1;
        java.sql.Connection conn = koneksi.getKoneksi();
        String sql = "SELECT * FROM nilai ORDER BY id_nilai DESC";
        java.sql.ResultSet rs = conn.createStatement().executeQuery(sql);
        
        while (rs.next()) {
            model.addRow(new Object[]{
                no++,
                rs.getString("nim"),
                rs.getString("nama_mk"),
                rs.getString("nilai_akhir"),
                rs.getString("grade")
            });
        }
        tblNilai.setModel(model); // Sesuaikan nama variabel tabelmu
    } catch (Exception e) {
        System.err.println("Gagal load data: " + e.getMessage());
    }
}
    private PdfPCell createCell(String text, Font font, int align) {
    PdfPCell cell = new PdfPCell(new Phrase(text, font));
    cell.setHorizontalAlignment(align);
    cell.setPadding(5);
    return cell;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNilai = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Data Nilai Mahasiswa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(43, 3, 0, 74);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Cari");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 124, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 41, 0, 0);
        getContentPane().add(txtCari, gridBagConstraints);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 124, 0, 0);
        getContentPane().add(btnRefresh, gridBagConstraints);

        btnTutup.setText("Tutup");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 29, 0, 0);
        getContentPane().add(btnTutup, gridBagConstraints);

        tblNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode MK", "Mata Kuliah", "SKS", "Score", "Grade"
            }
        ));
        jScrollPane1.setViewportView(tblNilai);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 456;
        gridBagConstraints.ipady = 287;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 124, 0, 74);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jButton1.setText("Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 124, 41, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
txtCari.setText("");
    loadData();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
String key = txtCari.getText();
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("NIM");
    model.addColumn("Mata Kuliah");
    model.addColumn("Score");
    model.addColumn("Grade");

    try {
        int no = 1;
        java.sql.Connection conn = koneksi.getKoneksi();
        String sql = "SELECT * FROM nilai WHERE nim LIKE '%" + key + "%' OR nama_mk LIKE '%" + key + "%'";
        java.sql.ResultSet rs = conn.createStatement().executeQuery(sql);
        
        while (rs.next()) {
            model.addRow(new Object[]{
                no++,
                rs.getString("nim"),
                rs.getString("nama_mk"),
                rs.getString("nilai_akhir"),
                rs.getString("grade")
            });
        }
        tblNilai.setModel(model);
    } catch (Exception e) {
        System.err.println("Gagal cari data: " + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int baris = tblNilai.getSelectedRow();
    if (baris == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data mahasiswa dulu!");
        return;
    }

    String nim = tblNilai.getValueAt(baris, 1).toString();
    String namaMhs = "";
    String semesterMhs = "-";
    
    // Lokasi simpan file
    String path = "KHS_" + nim + ".pdf";
    Document document = new Document(PageSize.A4);

    try {
        java.sql.Connection conn = koneksi.getKoneksi();
        
        // 1. Ambil Nama Mahasiswa
        String sqlMhs = "SELECT nama FROM mahasiswa WHERE nim='" + nim + "'";
        java.sql.ResultSet rsMhs = conn.createStatement().executeQuery(sqlMhs);
        if(rsMhs.next()) namaMhs = rsMhs.getString("nama");

        // 2. Inisialisasi PDF
        PdfWriter.getInstance(document, new FileOutputStream(path));
        document.open();

        // Font Settings
        Font fontHeader = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);
        Font fontAlamat = FontFactory.getFont(FontFactory.HELVETICA, 10);
        Font fontTabelHeader = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10);
        Font fontIsi = FontFactory.getFont(FontFactory.HELVETICA, 10);

        // Header Kampus
        Paragraph univ = new Paragraph("UNIVERSITAS TEKNOLOGI BANDUNG", fontHeader);
        univ.setAlignment(Element.ALIGN_CENTER);
        document.add(univ);
        
        Paragraph alamat = new Paragraph("Jl. Soekarno Hatta No.378 Bandung 40235\n", fontAlamat);
        alamat.setAlignment(Element.ALIGN_CENTER);
        document.add(alamat);
        
        document.add(new Paragraph("==========================================================================", fontAlamat));
        Paragraph judul = new Paragraph("DAFTAR NILAI MAHASISWA\n\n", fontTabelHeader);
        judul.setAlignment(Element.ALIGN_CENTER);
        document.add(judul);

        // 3. Ambil Data Nilai untuk Hitung IPS & Semester
        String sqlNilai = "SELECT n.nama_mk, m.kode_mk, m.sks, m.semester, m.nama_dosen, n.nilai_akhir, n.grade " +
                         "FROM nilai n JOIN matakuliah m ON n.nama_mk = m.nama_mk " +
                         "WHERE n.nim='" + nim + "'";
        java.sql.ResultSet rsNilai = conn.createStatement().executeQuery(sqlNilai);
        
        // Simpan data ke list dulu karena ResultSet hanya bisa dibaca sekali
        java.util.List<String[]> dataNilai = new java.util.ArrayList<>();
        double totalBobotSks = 0;
        int totalSksSemester = 0;
        
        while (rsNilai.next()) {
            if (dataNilai.isEmpty()) semesterMhs = rsNilai.getString("semester");
            
            String grade = rsNilai.getString("grade");
            int sks = rsNilai.getInt("sks");
            
            double bobot = 0;
            if (grade.equals("A")) bobot = 4.0;
            else if (grade.equals("AB")) bobot = 3.5;
            else if (grade.equals("B")) bobot = 3.0;
            else if (grade.equals("BC")) bobot = 2.5;
            else if (grade.equals("C")) bobot = 2.0;
            else if (grade.equals("D")) bobot = 1.0;

            totalBobotSks += (bobot * sks);
            totalSksSemester += sks;
            
            dataNilai.add(new String[]{
                rsNilai.getString("kode_mk"),
                rsNilai.getString("nama_mk"),
                rsNilai.getString("nama_dosen") == null ? "-" : rsNilai.getString("nama_dosen"),
                String.valueOf(sks),
                rsNilai.getString("nilai_akhir"),
                grade
            });
        }

        String ips = String.format("%.2f", (totalSksSemester == 0) ? 0.0 : totalBobotSks / totalSksSemester);

        // 4. Identitas Mahasiswa (Format 2 Kolom)
        PdfPTable tableId = new PdfPTable(4);
        tableId.setWidthPercentage(100);
        tableId.setWidths(new float[]{1.5f, 4f, 1.5f, 2f});
        tableId.getDefaultCell().setBorder(Rectangle.NO_BORDER);

        tableId.addCell(new Phrase("Nama", fontIsi)); tableId.addCell(new Phrase(": " + namaMhs.toUpperCase(), fontIsi));
        tableId.addCell(new Phrase("IPS", fontIsi));  tableId.addCell(new Phrase(": " + ips, fontIsi));
        
        tableId.addCell(new Phrase("NIM", fontIsi));  tableId.addCell(new Phrase(": " + nim, fontIsi));
        //tableId.addCell(new Phrase("IPK", fontIsi));  tableId.addCell(new Phrase(": " + ips, fontIsi));
        
        tableId.addCell(new Phrase("Angkatan", fontIsi)); tableId.addCell(new Phrase(": 2024", fontIsi));
                tableId.addCell(new Phrase("Prodi", fontIsi));    tableId.addCell(new Phrase(": Teknik Informatika", fontIsi));

        tableId.addCell(new Phrase("Semester", fontIsi)); tableId.addCell(new Phrase(": " + semesterMhs, fontIsi));
        tableId.addCell(new Phrase("", fontIsi));         tableId.addCell(new Phrase("", fontIsi));

        document.add(tableId);
        document.add(new Paragraph("\n"));

        // 5. Tabel Nilai
        PdfPTable table = new PdfPTable(new float[]{1, 2, 5, 4, 1.5f, 1.5f, 1.5f});
        table.setWidthPercentage(100);
        
        String[] headers = {"No", "Kode", "Matakuliah", "Dosen Pengampu", "SKS", "Nilai", "Grade"};
        for (String h : headers) {
            PdfPCell cell = new PdfPCell(new Phrase(h, fontTabelHeader));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setPadding(5);
            table.addCell(cell);
        }

        int no = 1;
        for (String[] row : dataNilai) {
            table.addCell(createCell(String.valueOf(no++), fontIsi, Element.ALIGN_CENTER));
            table.addCell(createCell(row[0], fontIsi, Element.ALIGN_CENTER));
            table.addCell(createCell(row[1], fontIsi, Element.ALIGN_LEFT));
            table.addCell(createCell(row[2], fontIsi, Element.ALIGN_LEFT));
            table.addCell(createCell(row[3], fontIsi, Element.ALIGN_CENTER));
            table.addCell(createCell(row[4], fontIsi, Element.ALIGN_CENTER));
            table.addCell(createCell(row[5], fontIsi, Element.ALIGN_CENTER));
        }

        document.add(table);
        document.add(new Paragraph("\nDicetak pada: " + new java.util.Date(), fontAlamat));
        
        document.close();
        
        javax.swing.JOptionPane.showMessageDialog(this, "PDF Berhasil Dibuat!");
        java.awt.Desktop.getDesktop().open(new java.io.File(path));

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menutup form ini?", 
            "Konfirmasi Tutup", 
            JOptionPane.YES_NO_OPTION);
            
    if (konfirmasi == JOptionPane.YES_OPTION) {
        this.dispose();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTutupActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTutup;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNilai;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
