/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pbo2uts;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import javax.swing.*;
import java.io.FileOutputStream;
import java.sql.*;
/**
 *
 * @author irsya
 */
public class FormDataKRS extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormDataKRS
     */
    public FormDataKRS() {
        initComponents();
        loadData();
    }
    private void loadData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("ID KRS");
    model.addColumn("NIM");
    model.addColumn("Nama Mahasiswa");
    model.addColumn("Kode MK");
    model.addColumn("Mata Kuliah");
    model.addColumn("Tahun Akademik");

    try {
        int no = 1;
        java.sql.Connection conn = koneksi.getKoneksi();
        // Query sakti untuk menggabungkan 3 tabel
        String sql = "SELECT krs.id_krs, krs.nim, mahasiswa.nama, krs.kode_mk, "
                   + "matakuliah.nama_mk, krs.thn_akademik "
                   + "FROM krs "
                   + "JOIN mahasiswa ON krs.nim = mahasiswa.nim "
                   + "JOIN matakuliah ON krs.kode_mk = matakuliah.kode_mk "
                   + "ORDER BY krs.id_krs DESC";
        
        java.sql.ResultSet rs = conn.createStatement().executeQuery(sql);
        
        while (rs.next()) {
            model.addRow(new Object[]{
                no++,
                rs.getString("id_krs"),
                rs.getString("nim"),
                rs.getString("nama"),
                rs.getString("kode_mk"),
                rs.getString("nama_mk"),
                rs.getString("thn_akademik")
            });
        }
        tblDataKrs.setModel(model);
    } catch (Exception e) {
        System.err.println("Gagal load data: " + e.getMessage());
    }
}
    private PdfPCell createCell(String text, Font font, int align) {
    PdfPCell cell = new PdfPCell(new Phrase(text, font));
    cell.setHorizontalAlignment(align);
    cell.setPadding(5);
    return cell;
}
    private void cariData(String key) {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("No");
    model.addColumn("ID KRS");
    model.addColumn("NIM");
    model.addColumn("Nama Mahasiswa");
    model.addColumn("Kode MK");
    model.addColumn("Mata Kuliah");
    model.addColumn("Tahun Akademik");

    try {
        int no = 1;
        java.sql.Connection conn = koneksi.getKoneksi();
        // Query JOIN ditambah filter WHERE untuk pencarian
        String sql = "SELECT krs.id_krs, krs.nim, mahasiswa.nama, krs.kode_mk, "
                   + "matakuliah.nama_mk, krs.thn_akademik "
                   + "FROM krs "
                   + "JOIN mahasiswa ON krs.nim = mahasiswa.nim "
                   + "JOIN matakuliah ON krs.kode_mk = matakuliah.kode_mk "
                   + "WHERE krs.nim LIKE '%" + key + "%' OR mahasiswa.nama LIKE '%" + key + "%' "
                   + "ORDER BY krs.id_krs DESC";
        
        java.sql.ResultSet rs = conn.createStatement().executeQuery(sql);
        
        while (rs.next()) {
            model.addRow(new Object[]{
                no++,
                rs.getString("id_krs"),
                rs.getString("nim"),
                rs.getString("nama"),
                rs.getString("kode_mk"),
                rs.getString("nama_mk"),
                rs.getString("thn_akademik")
            });
        }
        tblDataKrs.setModel(model);
    } catch (Exception e) {
        System.err.println("Gagal cari data: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataKrs = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnTutup = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("DATA KRS MAHASISWA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(86, 11, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 11, 0, 0);
        getContentPane().add(txtCari, gridBagConstraints);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 111, 0, 0);
        getContentPane().add(btnRefresh, gridBagConstraints);

        tblDataKrs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID KRS", "NIM", "Mahasiswa", "Kode MK", "Mata Kuliah", "Tahun Akademik"
            }
        ));
        jScrollPane1.setViewportView(tblDataKrs);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 541;
        gridBagConstraints.ipady = 303;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(18, 111, 0, 101);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel2.setText("Cari");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 111, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        btnTutup.setText("Tutup");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 28, 0, 0);
        getContentPane().add(btnTutup, gridBagConstraints);

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 111, 61, 0);
        getContentPane().add(btnCetak, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
cariData(txtCari.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariKeyReleased

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
txtCari.setText("");
    loadData();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
int konfirmasi = JOptionPane.showConfirmDialog(this, 
            "Apakah Anda yakin ingin menutup form ini?", 
            "Konfirmasi Tutup", 
            JOptionPane.YES_NO_OPTION);
            
    if (konfirmasi == JOptionPane.YES_OPTION) {
        this.dispose();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTutupActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
int row = tblDataKrs.getSelectedRow();
    if (row == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data mahasiswa di tabel dulu");
        return;
    }

    String nim = tblDataKrs.getValueAt(row, 2).toString();
    String namaMhs = tblDataKrs.getValueAt(row, 3).toString();
    String semesterKrs = "-";
    
    // Lokasi simpan file
    String path = "KRS_" + nim + ".pdf";
    Document document = new Document(PageSize.A4);

    try {
        java.sql.Connection conn = koneksi.getKoneksi();
        PdfWriter.getInstance(document, new FileOutputStream(path));
        document.open();

        // Font Settings
        Font fontHeader = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14);
        Font fontAlamat = FontFactory.getFont(FontFactory.HELVETICA, 10);
        Font fontTabelHeader = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10);
        Font fontIsi = FontFactory.getFont(FontFactory.HELVETICA, 10);

        // 1. Header Kampus
        Paragraph univ = new Paragraph("UNIVERSITAS TEKNOLOGI BANDUNG", fontHeader);
        univ.setAlignment(Element.ALIGN_CENTER);
        document.add(univ);
        
        Paragraph alamat = new Paragraph("Jl. Soekarno Hatta No.378 Bandung 40235\n", fontAlamat);
        alamat.setAlignment(Element.ALIGN_CENTER);
        document.add(alamat);
        
        document.add(new Paragraph("==========================================================================", fontAlamat));
        Paragraph judul = new Paragraph("KARTU RENCANA STUDI (KRS)\n\n", fontTabelHeader);
        judul.setAlignment(Element.ALIGN_CENTER);
        document.add(judul);

        // 2. Query Data KRS & Matakuliah
        String sql = "SELECT k.kode_mk, m.nama_mk, m.sks, m.semester, m.nama_dosen " +
                     "FROM krs k JOIN matakuliah m ON k.kode_mk = m.kode_mk " +
                     "WHERE k.nim = '" + nim + "'";
        java.sql.ResultSet rs = conn.createStatement().executeQuery(sql);
        
        java.util.List<String[]> dataKrs = new java.util.ArrayList<>();
        int totalSks = 0;
        
        while (rs.next()) {
            if (dataKrs.isEmpty()) semesterKrs = rs.getString("semester");
            int sks = rs.getInt("sks");
            totalSks += sks;
            
            dataKrs.add(new String[]{
                rs.getString("kode_mk"),
                rs.getString("nama_mk"),
                rs.getString("nama_dosen") == null ? "-" : rs.getString("nama_dosen"),
                String.valueOf(sks)
            });
        }

        // 3. Identitas Mahasiswa (Sejajar Kiri-Kanan)
        PdfPTable tableId = new PdfPTable(4);
        tableId.setWidthPercentage(100);
        tableId.setWidths(new float[]{1.5f, 4f, 1.5f, 2f});
        tableId.getDefaultCell().setBorder(Rectangle.NO_BORDER);

        tableId.addCell(new Phrase("Nama", fontIsi));      tableId.addCell(new Phrase(": " + namaMhs.toUpperCase(), fontIsi));
        tableId.addCell(new Phrase("Semester", fontIsi));  tableId.addCell(new Phrase(": " + semesterKrs, fontIsi));
        
        tableId.addCell(new Phrase("NIM", fontIsi));       tableId.addCell(new Phrase(": " + nim, fontIsi));
        tableId.addCell(new Phrase("Tahun", fontIsi));     tableId.addCell(new Phrase(": 2026", fontIsi));
        
        tableId.addCell(new Phrase("Prodi", fontIsi));     tableId.addCell(new Phrase(": Teknik Informatika", fontIsi));
        tableId.addCell(new Phrase("Total SKS", fontIsi)); tableId.addCell(new Phrase(": " + totalSks, fontIsi));

        document.add(tableId);
        document.add(new Paragraph("\n"));

        // 4. Tabel KRS
        PdfPTable table = new PdfPTable(new float[]{1, 2, 5, 4, 1.5f});
        table.setWidthPercentage(100);
        
        String[] headers = {"No", "Kode", "Mata Kuliah", "Dosen Pengampu", "SKS"};
        for (String h : headers) {
            PdfPCell cell = new PdfPCell(new Phrase(h, fontTabelHeader));
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setPadding(5);
            table.addCell(cell);
        }

        int no = 1;
        for (String[] r : dataKrs) {
            table.addCell(createCell(String.valueOf(no++), fontIsi, Element.ALIGN_CENTER));
            table.addCell(createCell(r[0], fontIsi, Element.ALIGN_CENTER));
            table.addCell(createCell(r[1], fontIsi, Element.ALIGN_LEFT));
            table.addCell(createCell(r[2], fontIsi, Element.ALIGN_LEFT));
            table.addCell(createCell(r[3], fontIsi, Element.ALIGN_CENTER));
        }

        document.add(table);
        
        // 5. Footer & Tanda Tangan
        document.add(new Paragraph("\n"));
        String tgl = new java.text.SimpleDateFormat("dd MMMM yyyy").format(new java.util.Date());
        Paragraph ttd = new Paragraph("Bandung, " + tgl + "\n\n\n\n( ____________________ )\nPetugas Akademik", fontIsi);
        ttd.setAlignment(Element.ALIGN_RIGHT);
        document.add(ttd);

        document.close();
        
        javax.swing.JOptionPane.showMessageDialog(this, "KRS Berhasil Disimpan ke PDF!");
        java.awt.Desktop.getDesktop().open(new java.io.File(path));

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error KRS: " + e.getMessage());
    }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCetakActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDataKrs;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
