/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbo2uts;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.JPasswordField;
/**
 *
 * @author irsya
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        initComponents();
 this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        Txtusername.putClientProperty("JTextField.placeholderText", "Masukkan Username");
        Txtusername.putClientProperty("JTextField.showClearButton", true);
        jpw.putClientProperty("JTextField.placeholderText", "Masukkan Password");
        jpw.putClientProperty("JTextField.showClearButton", true);
        //jpw.putClientProperty("JPasswordField.showRevealButton", true);
        //jpw.putClientProperty("JPasswordField.revealIcon", "eye");
    
    

    jlogin.putClientProperty("FlatLaf.style", "pressedBackground: #38b6ff; foreground: #ffffff");
    jlogin.putClientProperty("FlatLaf.style", "hoverBackground: #1a73e8; pressedBackground: #0d47a1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Txtusername = new javax.swing.JTextField();
        jlogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpw = new javax.swing.JPasswordField();
        checkShow = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtusernameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 92;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 10, 0, 390);
        getContentPane().add(Txtusername, gridBagConstraints);

        jlogin.setText("Login");
        jlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 79;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 401, 0);
        getContentPane().add(jlogin, gridBagConstraints);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo2uts/Asset/Person.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 350, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Welcome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(380, 30, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbo2uts/Asset/Password.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 350, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 10, 0, 0);
        getContentPane().add(jpw, gridBagConstraints);

        checkShow.setText("Show Password");
        checkShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkShowActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 0, 0);
        getContentPane().add(checkShow, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtusernameActionPerformed

    private void checkShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkShowActionPerformed
     if (checkShow.isSelected()) {
        // Menampilkan password (karakter 0 berarti teks asli)
        jpw.setEchoChar((char)0);
    } else {
        // Menyembunyikan kembali (menggunakan karakter bintang atau titik)
        jpw.setEchoChar('•'); 
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_checkShowActionPerformed

    private void jloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginActionPerformed
String user = Txtusername.getText();
    String pass = new String(jpw.getPassword()); 

    // 1. Validasi input kosong
    if (user.isEmpty() || pass.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Username dan Password tidak boleh kosong,");
        return;
    }

    try {
        // Panggil koneksi
        java.sql.Connection conn = koneksi.getKoneksi();
        
        // 2. Query mencari user berdasarkan username dan password
        String sql = "SELECT * FROM users WHERE username=? AND password=?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, user);
        pst.setString(2, pass);
        java.sql.ResultSet rs = pst.executeQuery();

        // 3. Cek apakah data ditemukan
        if (rs.next()) {
            // --- LOGIN BERHASIL ---
            
            // 4. TITIP DATA KE SESSION (Sangat Penting untuk Hak Akses)
            // Pastikan kolom di database namanya 'username' dan 'level'
            Session.setUsername(rs.getString("username"));
            Session.setLevel(rs.getString("level"));

            javax.swing.JOptionPane.showMessageDialog(this, "Login Berhasil! Selamat datang " + user);

            // 5. MEMANGGIL MENU UTAMA
            MenuUtamaa utama = new MenuUtamaa();
            
            // Tengahkan Menu Utama (Opsional)
            utama.setLocationRelativeTo(null); 
            
            // Tampilkan Menu Utama
            utama.setVisible(true);
            
            // 6. TUTUP FORM LOGIN
            this.dispose(); 
            
        } else {
            // --- LOGIN GAGAL ---
            javax.swing.JOptionPane.showMessageDialog(this, "Username atau Password salah!");
            
            // Reset form
            jpw.setText("");
            Txtusername.setText("");
            Txtusername.requestFocus();
        }

    } catch (Exception e) {
        // Menampilkan error jika database tidak terkoneksi atau query salah
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jloginActionPerformed

  
    public static void main(String args[]) {
        try {

    UIManager.setLookAndFeel( new FlatMacDarkLaf() );
    UIManager.put( "Button.arc", 20 );
    UIManager.put( "Component.arc", 20 );
    
    
} catch( Exception ex ) {
    System.err.println( "Failed to initialize LaF" );
}
        if (koneksi.getKoneksi() != null) {
        System.out.println("TEST: Jembatan Aman!");
    } else {
        System.out.println("TEST: Jembatan Putus!");
    }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txtusername;
    private javax.swing.JCheckBox checkShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jlogin;
    private javax.swing.JPasswordField jpw;
    // End of variables declaration//GEN-END:variables
}
