/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pbo2uts;

public class FormChangePassword extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormChangePassword
     */
    public FormChangePassword() {
        initComponents();
        txtPwLama.putClientProperty("JTextField.placeholderText", "Password Lama");
        txtPwLama.putClientProperty("JTextField.showClearButton", true);
        txtBaru.putClientProperty("JTextField.placeholderText", "Password Baru");
        txtBaru.putClientProperty("JTextField.showClearButton", true);
        txtPwBaru.putClientProperty("JTextField.placeholderText", "Konfirmasi Password");
        txtPwBaru.putClientProperty("JTextField.showClearButton", true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txtPwLama = new javax.swing.JTextField();
        txtBaru = new javax.swing.JTextField();
        txtPwBaru = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        txtPwLama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPwLamaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 143, 0, 125);
        getContentPane().add(txtPwLama, gridBagConstraints);

        txtBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBaruActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 143, 0, 125);
        getContentPane().add(txtBaru, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 143, 0, 125);
        getContentPane().add(txtPwBaru, gridBagConstraints);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 143, 87, 125);
        getContentPane().add(btnUpdate, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPwLamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPwLamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPwLamaActionPerformed

    private void txtBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBaruActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

    String passLama = txtPwLama.getText();
    String passBaru = txtBaru.getText();
    String konfirmasi = txtPwBaru.getText();

    // 2. Validasi input kosong
    if (passLama.isEmpty() || passBaru.isEmpty() || konfirmasi.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Semua field harus diisi");
        return;
    }

    // 3. Validasi kecocokan password baru
    if (!passBaru.equals(konfirmasi)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Konfirmasi Password tidak cocok!");
        return;
    }

    try {
        java.sql.Connection conn = koneksi.getKoneksi();
        
        // 4. Cek apakah password lama benar berdasarkan username yang sedang login
        String sqlCek = "SELECT * FROM users WHERE username=? AND password=?";
        java.sql.PreparedStatement pstCek = conn.prepareStatement(sqlCek);
        pstCek.setString(1, Session.getUsername()); 
        pstCek.setString(2, passLama);
        java.sql.ResultSet rs = pstCek.executeQuery();

        if (rs.next()) {
            // 5. Jika password lama benar, lakukan update
            String sqlUp = "UPDATE users SET password=? WHERE username=?";
            java.sql.PreparedStatement pstUp = conn.prepareStatement(sqlUp);
            pstUp.setString(1, passBaru);
            pstUp.setString(2, Session.getUsername());
            pstUp.executeUpdate();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Password Berhasil Diperbarui!");
            this.dispose(); // Tutup form setelah berhasil
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Password Lama Salah!");
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField txtBaru;
    private javax.swing.JTextField txtPwBaru;
    private javax.swing.JTextField txtPwLama;
    // End of variables declaration//GEN-END:variables
}
